### ISSUE TITLE
Light controls

### ISSUE THREAD

**Issue by ToeiRei** [betaboon/philips-airpurifier#35]
Can you please add a way to change the display brightness as it would make my life a bit easier when I'm able to automatically dim the display at night.

**Comment by kongo09** [comment]
This does exist already. Here is my script that I use to do this for my devices:
```
alias: Toggle AC light
sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ is_state(entity_id, "on") }}'
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ not is_state_attr(entity_id, "display_backlight",
                      false) }}
                sequence:
                  - service: philips_airpurifier.set_display_backlight_off
                    data:
                      entity_id: '{{ entity_id }}'
                  - service: philips_airpurifier.set_light_brightness
                    data:
                      entity_id: '{{ entity_id }}'
                      brightness: 0
            default:
              - service: philips_airpurifier.set_display_backlight_on
                data:
                  entity_id: '{{ entity_id }}'
              - service: philips_airpurifier.set_light_brightness
                data:
                  entity_id: '{{ entity_id }}'
                  brightness: 100
mode: single
icon: 'pap:light_dimming_button'
fields:
  entity_id:
    description: Entity of fan
    example: fan.air_ac2729
description: Toggle the backlight of philips AC
```
